### PR TITLE
T-shirt Ideas for KS Linux Fest

### PR DESCRIPTION
**Pull request by chris-welchhans**
Added PNG versions, for easier previewing.

Rather than convert the fonts to paths, (in the SVG,) I left them as text so that other contributors can make changes. The PNGs show the fonts as intended, for those who don't have the fonts installed.

This commit also includes a zip file with the two Google Fonts (http://www.google.com/fonts/) used in the designs.

### CODE REVIEW

**Comment by h4ck3rm1k3** [comment]
thanks, we should send these to the list for review and get some printed.

**Comment by chris-welchhans** [comment]
Feel free to use these however you wish. If you decide to use one, or want to see changes, etc., I'd be glad to help with that. I can help get the artwork ready for printing and even mock up some shirts to help choose shirt/ink colors. When it comes to printing the shirts, I recommend Happy Shirt, (if you don't already have a vendor for that.) I've worked with them before and was happy with the results.

**Comment by h4ck3rm1k3** [comment]
ok, well if you can help out, i am totally overloaded here right now.

**Comment by chris-welchhans** [comment]
If you want me to post/put these somewhere where they can be reviewed, let me know where.

**Comment by h4ck3rm1k3** [comment]
I posted the svg on the site now you want to make a page for them ?
Teeshirts.md and post the pngs. We could setup an order page.

On Tue, Mar 3, 2015 at 2:54 PM, chris-welchhans notifications@github.com
wrote:

> If you want me to post/put these somewhere where they can be reviewed, let
> me know where.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/KansasLinuxFest/website/pull/5#issuecomment-77032314.

## 

James Michael DuPont
Member of Free Libre Open Source Software Kosova http://www.flossk.org
Saving Wikipedia(tm) articles from deletion http://SpeedyDeletion.wikia.com

**Comment by chris-welchhans** [comment]
I can work on setting up a page with these. I should have some time this evening.

**Comment by h4ck3rm1k3** [comment]
Ok, I am also goign to start working on flyers and stuff soon!

**Comment by chris-welchhans** [comment]
I started on the page last night. Were you thinking this page would be a place to review the designs? I made some t-shirt mock-ups with each design and different colors, (ink and shirt colors.) If I put up that page with all the variations, would that be helpful or do we just need to pick one and put it up an order form? Sorry to bombard you with so many questions--I know you have a lot on your plate.

**Comment by h4ck3rm1k3** [comment]
ok, i already did the page http://www.kansaslinuxfest.us/pages/media.html is that ok?

**Comment by chris-welchhans** [comment]
Sure, no problem. I made a small change to one of the images and added a new design. I updated the media page and uploaded the updated files.

**Comment by h4ck3rm1k3** [comment]
http://www.kansaslinuxfest.us/pages/media.html ok that is live, i like it. What do you say we setup a page for them to order them online?

**Comment by chris-welchhans** [comment]
I'd be happy to help with that. Did you have something in mind? Were you thinking of using an online shop, such as Cafe Press? Or were you wanting to gather orders and have them printed locally?

**Comment by h4ck3rm1k3** [comment]
Ideally we would have them printed locally and people would order online. we can also order at least one per speaker and another 20 for sale at risk.

**Comment by chris-welchhans** [comment]
I would suggest offering one design, in one color, for online ordering, speakers' shirts, and shirts for sale. Also, if you use a design without the date on it, (or any reference to date, e.g. "1st Annual",) you could sell any leftovers next year. That leaves the first design, or I could take the date off the fourth design. Since the other designs are on the site, we could provide a link to Acme's website and attendees could have the option of printing their own shirts there, if they want a different design, or different shirt/ink colors.
We used Happy Shirt last year and they did a nice job. The shirts ended up being about $8 per shirt, for two colors, for about 35 shirts. They had a $25 setup fee, and $10 or $12 per color (for each screen), plus shirt cost. I think that's pretty standard. I've used other places in the past and they had a similar price structure. They also had a quick turnaround.
Do you have anything in mind for ordering online? Something that works with the CMS you're using for the festival website?

**Comment by h4ck3rm1k3** [comment]
I am using static hosting for the site. Anything static is fine. We could just make a page with a paypal link. For the ordering, I want to get one for each speaker in one color. On per staff (10) and then get another 20 on risk + order. Sure they can choose the design as well, why not!

**Comment by h4ck3rm1k3** [comment]
@chris-welchhans  please drop me a mail at mdupont@kansaslinuxfest.us and lets talk about this offline.

**Pull request merged**
